<a href="https://colab.research.google.com/github/Nikhilsankhyan0/Agrisheild-AI/blob/main/AgriShield_preporcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [147]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [148]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('/content/drive/MyDrive/agrishield_ai_loan_dataset.csv')
df.shape

(20040, 60)

In [149]:
df.head()

,Farmer_ID,Application_Date,Age,Gender,Education_Level,Marital_Status,Family_Size,Dependents,Farming_Experience_Years,State,...,EMI,Income_Stability_Index,Farm_Productivity_Index,Climate_Risk_Index,Financial_Health_Index,Loan_Affordability_Index,Asset_Strength_Index,Overall_Risk_Factor,Risk_Score,Loan_Status
0,AGR117544,23-06-2023,53.0,Male,Higher Secondary,Married,8.0,4.0,NaN,Kerala,...,4506.78,40.7,52.5,65.4,57.7,65.5,48.5,73.2,40.6,Approved with Conditions
1,AGR103888,02-10-2022,39.0,Female,Illiterate,Married,8.0,3.0,21.0,Jharkhand,...,951.98,55.4,53.3,35.1,70.3,72.2,43.7,52.0,54.7,Approved
2,AGR112882,17-07-2024,27.0,Male,Secondary,Married,8.0,3.0,9.0,Madhya Pradesh,...,10895.49,50.5,44.4,48.4,50.3,41.5,46.8,95.8,22.7,Rejected
3,AGR108149,26-07-2024,41.0,Male,Post Graduate,Married,6.0,3.0,22.0,Haryana,...,524.61,52.3,56.5,49.5,0.0,13.1,46.2,100.0,20.8,Rejected
4,AGR115346,24-04-2022,33.0,Male,Primary,Married,NaN,3.0,12.0,Gujarat,...,1220.20,39.6,32.7,47.3,59.6,79.5,49.9,65.8,34.6,Approved with Conditions

In [150]:
df.tail()

,Farmer_ID,Application_Date,Age,Gender,Education_Level,Marital_Status,Family_Size,Dependents,Farming_Experience_Years,State,...,EMI,Income_Stability_Index,Farm_Productivity_Index,Climate_Risk_Index,Financial_Health_Index,Loan_Affordability_Index,Asset_Strength_Index,Overall_Risk_Factor,Risk_Score,Loan_Status
20035,AGR117677,21-04-2021,46.0,Male,Primary,Married,6.0,3.0,29.0,Tamil Nadu,...,1664.33,50.5,61.4,52.8,14.8,19.1,NaN,100.0,16.1,Rejected
20036,AGR104023,17-06-2021,45.0,Male,Secondary,Married,8.0,4.0,24.0,Chhattisgarh,...,5595.50,63.7,61.7,0.0,56.4,51.8,59.4,54.0,31.8,Rejected
20037,AGR107259,04-05-2022,31.0,Male,Higher Secondary,Married,5.0,3.0,10.0,Punjab,...,958.36,54.1,59.4,43.5,65.8,66.8,51.1,67.9,52.9,Approved
20038,AGR103775,05-11-2023,43.0,Male,Graduate,Married,5.0,2.0,25.0,Maharashtra,...,10841.73,49.5,50.7,19.5,64.4,0.0,41.7,74.5,38.5,Approved with Conditions
20039,AGR110137,05-12-2025,66.0,Male,Secondary,Married,9.0,3.0,51.0,Telangana,...,42816.16,60.0,54.6,35.5,38.4,42.4,49.8,91.6,26.1,Rejected

In [151]:

duplicate_columns = [
    col for col in df.columns
    if col != 'Farmer_ID'
]

print(
    "Duplicate application profiles:",
    df.duplicated(subset=duplicate_columns).sum()
)

df = df.drop_duplicates(
    subset=duplicate_columns,
    keep='first'
).reset_index(drop=True)

print("Shape after duplicate removal:", df.shape)

Duplicate application profiles: 40
Shape after duplicate removal: (20000, 60)

In [152]:
print("No. of columns :",len(df.columns))
print("No. of rows :",len(df))

No. of columns : 60
No. of rows : 20000

splitting the data set into x and y features

In [153]:
x=df.drop(columns=['Risk_Score','Loan_Status'])
y_regression=df['Risk_Score']
y_classification=df['Loan_Status']

In [154]:
print(y_regression.head())
print(y_classification.head())

0    40.6
1    54.7
2    22.7
3    20.8
4    34.6
Name: Risk_Score, dtype: float64
0    Approved with Conditions
1                    Approved
2                    Rejected
3                    Rejected
4    Approved with Conditions
Name: Loan_Status, dtype: object

splitting the dataset into 70% training , 30 temporary (15 validation ,15 test)

In [155]:
from sklearn.model_selection import train_test_split
x_train , x_temp , y_train_reg , y_temp_reg , y_train_cls , y_temp_cls= train_test_split(x,
                                                                                            y_regression,
                                                  y_classification,

                                                  test_size=0.3,random_state=42,
                                                  stratify=y_classification)

spliting the 30% into validation and testing

In [157]:
x_val, x_test, y_val_reg, y_test_reg, y_val_cls, y_test_cls = train_test_split(
    x_temp,
    y_temp_reg, # This contains the numerical Risk_Score for the temporary set
    y_temp_cls, # This contains the categorical Loan_Status for the temporary set
    test_size=0.50,
    random_state=42,
    stratify=y_temp_cls # Correct: Stratify on the classification target (Loan_Status)
)

In [159]:
print("Shape of x_train:", x_train.shape)
print("Shape of x_val:", x_val.shape)
print("Shape of x_test:", x_test.shape)
print("Shape of y_train_reg:", y_train_reg.shape)
print("Shape of y_val_reg:", y_val_reg.shape)
print("Shape of y_test_reg:", y_test_reg.shape)
print("Shape of y_train_cls:", y_train_cls.shape)
print("Shape of y_val_cls:", y_val_cls.shape)
print("Shape of y_test_cls:", y_test_cls.shape)

Shape of x_train: (14000, 58)
Shape of x_val: (3000, 58)
Shape of x_test: (3000, 58)
Shape of y_train_reg: (14000,)
Shape of y_val_reg: (3000,)
Shape of y_test_reg: (3000,)
Shape of y_train_cls: (14000,)
Shape of y_val_cls: (3000,)
Shape of y_test_cls: (3000,)

handling missing values

In [160]:
numerical_cols=x_train.select_dtypes(include=['int64','float64']).columns.tolist()
category_cols=x_train.select_dtypes(include=['object']).columns.tolist()

In [161]:
for col in numerical_cols:
  median_value=x_train[col].median()
  x_train[col]=x_train[col].fillna(median_value)
  x_val[col]=x_val[col].fillna(median_value)
  x_test[col]= x_test[col].fillna(median_value)

In [162]:
for col in category_cols:

    x_train[col] = x_train[col].fillna('Unknown')
    x_val[col] = x_val[col].fillna('Unknown')
    x_test[col] = x_test[col].fillna('Unknown')

In [163]:
print("Train missing:", x_train.isna().sum().sum())
print("Validation missing:", x_val.isna().sum().sum())
print("Test missing:", x_test.isna().sum().sum())

Train missing: 0
Validation missing: 0
Test missing: 0

clean/remove columns before encoding

In [164]:
x_train=x_train.drop(columns='Farmer_ID')
x_val=x_val.drop(columns='Farmer_ID')
x_test=x_test.drop(columns='Farmer_ID')

feature extration from application date into year , month , day , quater or month , day of week

In [165]:
for data in [x_train, x_val, x_test]:

    data['Application_Date'] = pd.to_datetime(
        data['Application_Date'],
        errors='coerce'
    )

/tmp/ipykernel_1106/1411565754.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data['Application_Date'] = pd.to_datetime(
/tmp/ipykernel_1106/1411565754.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data['Application_Date'] = pd.to_datetime(
/tmp/ipykernel_1106/1411565754.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data['Application_Date'] = pd.to_datetime(

In [166]:
for data in [x_train, x_val, x_test]:

    data['Application_Year'] = data['Application_Date'].dt.year
    data['Application_Month'] = data['Application_Date'].dt.month
    data['Application_Day'] = data['Application_Date'].dt.day
    data['Application_DayOfWeek'] = data['Application_Date'].dt.dayofweek
    data['Application_Quarter'] = data['Application_Date'].dt.quarter

In [167]:
print(x_train[
    [
        'Application_Date',
        'Application_Year',
        'Application_Month',
        'Application_Day',
        'Application_DayOfWeek',
        'Application_Quarter'
    ]
].head())

      Application_Date  Application_Year  Application_Month  Application_Day  \
19181       2021-11-14              2021                 11               14
12906       2022-05-28              2022                  5               28
10731       2023-08-09              2023                  8                9
15511       2025-02-06              2025                  2                6
16690       2024-02-02              2024                  2                2

       Application_DayOfWeek  Application_Quarter
19181                      6                    4
12906                      5                    2
10731                      2                    3
15511                      3                    1
16690                      4                    1

In [168]:
x_train = x_train.drop(columns=['Application_Date'])
x_val = x_val.drop(columns=['Application_Date'])
x_test = x_test.drop(columns=['Application_Date'])

In [185]:
numerical_cols = x_train.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = x_train.select_dtypes(include=['object']).columns.tolist()

print("Updated Numerical columns:", len(numerical_cols))
print("Updated Categorical columns:", len(category_cols))
print("\nUpdated Categorical columns list:")
print(categorical_cols)

Updated Numerical columns: 35
Updated Categorical columns: 21

Updated Categorical columns list:
['Gender', 'Education_Level', 'Marital_Status', 'State', 'District', 'Land_Ownership', 'Soil_Type', 'Irrigation_Availability', 'Primary_Crop', 'Secondary_Crop', 'Flood_Risk', 'Drought_Risk', 'Cyclone_Risk', 'Pest_Risk', 'Climate_Zone', 'Crop_Insurance', 'Government_Subsidy', 'MSP_Eligible', 'Tractor_Ownership', 'Previous_Default', 'Loan_Purpose']

In [169]:
derived_features = [
    'Income_Stability_Index',
    'Farm_Productivity_Index',
    'Climate_Risk_Index',
    'Financial_Health_Index',
    'Loan_Affordability_Index',
    'Asset_Strength_Index',
    'Overall_Risk_Factor'
]

In [170]:
for col in derived_features:
  print(col, "->" , col in x_train.columns)

Income_Stability_Index -> True
Farm_Productivity_Index -> True
Climate_Risk_Index -> True
Financial_Health_Index -> True
Loan_Affordability_Index -> True
Asset_Strength_Index -> True
Overall_Risk_Factor -> True

checking correlation with derived features

In [175]:
correlation = x_train[
    derived_features
].copy()

# Assign the numerical Risk_Score from y_train_reg (which now correctly holds the regression target)
correlation['Risk_Score'] = y_train_reg.values

print(
    correlation.corr()['Risk_Score']
    .sort_values(ascending=False)
)

Risk_Score                  1.000000
Financial_Health_Index      0.654841
Loan_Affordability_Index    0.369202
Income_Stability_Index      0.309833
Farm_Productivity_Index     0.195744
Asset_Strength_Index        0.032582
Climate_Risk_Index         -0.219381
Overall_Risk_Factor        -0.711020
Name: Risk_Score, dtype: float64

In [173]:
print(y_train_reg)

19181    51.6
12906    39.7
10731    50.2
15511    49.9
16690     0.0
         ...
17859    13.9
9504     37.9
8438     59.7
7571     40.6
6157     37.9
Name: Risk_Score, Length: 14000, dtype: float64

In [174]:
temp = x_train[
    derived_features
].copy()

temp['Loan_Status'] = y_train_cls.values

print(temp.groupby('Loan_Status')[derived_features].mean().T)

Loan_Status                Approved  Approved with Conditions   Rejected
Income_Stability_Index    57.500252                 53.408281  50.339483
Farm_Productivity_Index   57.764049                 54.960840  51.901927
Climate_Risk_Index        29.994799                 34.381674  39.734054
Financial_Health_Index    64.540773                 59.741598  40.169495
Loan_Affordability_Index  64.154153                 57.489920  44.487239
Asset_Strength_Index      51.362080                 50.906189  50.863784
Overall_Risk_Factor       58.839611                 64.964903  82.363549

In [176]:
print("DERIVED FEATURES")
print(derived_features)

print("\nData types:")
print(x_train[derived_features].dtypes)

DERIVED FEATURES
['Income_Stability_Index', 'Farm_Productivity_Index', 'Climate_Risk_Index', 'Financial_Health_Index', 'Loan_Affordability_Index', 'Asset_Strength_Index', 'Overall_Risk_Factor']

Data types:
Income_Stability_Index      float64
Farm_Productivity_Index     float64
Climate_Risk_Index          float64
Financial_Health_Index      float64
Loan_Affordability_Index    float64
Asset_Strength_Index        float64
Overall_Risk_Factor         float64
dtype: object

encoding

In [177]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(handle_unknown='ignore',sparse_output=False)

In [188]:
# Convert categorical columns to string type to ensure uniformity for the encoder
x_train[categorical_cols] = x_train[categorical_cols].astype(str)
x_val[categorical_cols] = x_val[categorical_cols].astype(str)
x_test[categorical_cols] = x_test[categorical_cols].astype(str)

x_train_encoded = encoder.fit_transform(x_train[categorical_cols])
x_val_encoded = encoder.transform(x_val[categorical_cols])
x_test_encoded = encoder.transform(x_test[categorical_cols])

# Get feature names for the encoded columns
encoded_feature_names = encoder.get_feature_names_out(categorical_cols)

print("Shape of x_train_encoded:", x_train_encoded.shape)
print("Shape of x_val_encoded:", x_val_encoded.shape)
print("Shape of x_test_encoded:", x_test_encoded.shape)

Shape of x_train_encoded: (14000, 245)
Shape of x_val_encoded: (3000, 245)
Shape of x_test_encoded: (3000, 245)

convert the arrays into dataframe

In [189]:
encoded_feature_names = encoder.get_feature_names_out(
    categorical_cols
)

x_train_encoded = pd.DataFrame(
    x_train_encoded,
    columns=encoded_feature_names,
    index=x_train.index
)

x_val_encoded = pd.DataFrame(
    x_val_encoded,
    columns=encoded_feature_names,
    index=x_val.index
)

x_test_encoded = pd.DataFrame(
    x_test_encoded,
    columns=encoded_feature_names,
    index=x_test.index
)

In [190]:
x_train_final = pd.concat(
    [
        x_train[numerical_cols],
        x_train_encoded
    ],
    axis=1
)

x_val_final = pd.concat(
    [
        x_val[numerical_cols],
        x_val_encoded
    ],
    axis=1
)

x_test_final = pd.concat(
    [
        x_test[numerical_cols],
        x_test_encoded
    ],
    axis=1
)

In [191]:
print("Train:", x_train_final.shape)
print("Validation:", x_val_final.shape)
print("Test:", x_test_final.shape)

print("\nMissing values:")
print("Train:", x_train_final.isnull().sum().sum())
print("Validation:", x_val_final.isnull().sum().sum())
print("Test:", x_test_final.isnull().sum().sum())

Train: (14000, 280)
Validation: (3000, 280)
Test: (3000, 280)

Missing values:
Train: 0
Validation: 0
Test: 0

In [196]:
x_train_final.to_csv(
    '/content/drive/MyDrive/X_train_encoded.csv',
    index=False
)

x_val_final.to_csv(
    '/content/drive/MyDrive/X_val_encoded.csv',
    index=False
)

x_test_final.to_csv(
    '/content/drive/MyDrive/X_test_encoded.csv',
    index=False
)

classification target

In [198]:
y_train_cls.to_csv(
    '/content/drive/MyDrive/y_train_cls.csv',
    index=False
)

y_val_cls.to_csv(
    '/content/drive/MyDrive/y_val_cls.csv',
    index=False
)

y_test_cls.to_csv(
    '/content/drive/MyDrive/y_test_cls.csv',
    index=False
)

regression target

In [199]:
y_train_reg.to_csv(
    '/content/drive/MyDrive/y_train_reg.csv',
    index=False
)

y_val_reg.to_csv(
    '/content/drive/MyDrive/y_val_reg.csv',
    index=False
)

y_test_reg.to_csv(
    '/content/drive/MyDrive/y_test_reg.csv',
    index=False
)